# VPN defaults
vpnName: vpn
vpnPort: 600
mtuSetting: 1320
# Update defaults
audioGitRepo: https://github.com/jpa-rocha/snd_hda_macbookpro.git
bluetoothGitRepo: https://github.com/jpa-rocha/macbook12-bluetooth-driver.git
reboot: true
